name: Cypress Tests

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ui-chrome-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.17.0
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: UI Functional Tests - Chrome 
        uses: cypress-io/github-action@v6
        with:
          build: npx cypress info
          browser: chrome
          record: true
          spec: cypress/tests/ui/*
          config-file: cypress.config.ts