name: Cypress Tests

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ui-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.17.0
      options: --user 1001
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: npx cypress info
      - run: node --version

      - name: Run Cypress tests
        run: npx cypress run